services:
  ws:
    build:
      context: .
      dockerfile: ./docker/ws/Dockerfile
    ports:
      - "3001:3001"
    restart: always
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    restart: always
