services:
  # ws:
  #   build:
  #     context: .
  #     dockerfile: ./docker/ws/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   restart: always
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: always
  #   environment:
  #     DATABASE_URL: postgresql://postgres:admin@db:5432/postgres

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  db_data:
    driver: local
